# Generated by Django 5.0.1 on 2024-02-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_food', '0002_category_product_delete_mahsul'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='off',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offprice',
            field=models.IntegerField(null=True),
        ),
    ]
